### ISSUE TITLE
Missing support for Chrome on IOS

### ISSUE THREAD

**Issue by ew73** [oalders/http-browserdetect#102]
Chrome on an iOS device (iphone, ipad, etc.) is mistakenly identified as a Safari browser.  The useragent string for Chrome includes a "CriOS":

An example:

    Mozilla/5.0 (iPhone; U; CPU iPhone OS 5_1_1 like Mac OS X; en) AppleWebKit/534.46.0 (KHTML, like Gecko) CriOS/19.0.1084.60 Mobile/9B206 Safari/7534.48.3

Source: https://developer.chrome.com/multidevice/user-agent

**Comment by oalders** [comment]
Thanks for this!  If you're motivated to provide a patch, we'll happily accept it. :)

**Comment by oalders** [comment]
Closed via 1097469b
