### ISSUE TITLE
Use of uninitialized value in lc at ... HTTP/BrowserDetect.pm line 449

### ISSUE THREAD

**Issue by maksudnurullaev** [oalders/http-browserdetect#106]
Hi,

I used mojolicious + morbo for test my project and time by time morbo server cat this issue:

Use of uninitialized value in lc at /home/ubuntu/perl5/perlbrew/perls/perl-5.18.4/lib/site_perl/5.18.4/HTTP/BrowserDetect.pm line 449, <DATA> line 2231.
Use of uninitialized value in lc at /home/ubuntu/perl5/perlbrew/perls/perl-5.18.4/lib/site_perl/5.18.4/HTTP/BrowserDetect.pm line 449.

**Comment by oalders** [comment]
@maksudnurullaev thanks for this.  I'd need more information from you.  Can you try running your app with https://metacpan.org/pod/Devel::Confess enabled and past a stacktrace to this issue?

**Comment by maksudnurullaev** [comment]
Ok, I installed "Devel::Confess" package and will send you logs when this issue happens again!

**Comment by maksudnurullaev** [comment]
It's strange, no more errors now! Sorry :-(

**Comment by oalders** [comment]
OK.  :)  Feel free to re-open if that changes.
