### ISSUE TITLE
Microsoft Edge is identified as Google Chrome

### ISSUE THREAD

**Issue by danielslave** [oalders/http-browserdetect#109]
Hello,

Latest IE version, Microsoft Edge is identified as Google Chome

Sample UA:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10162

**Comment by oalders** [comment]
Closed via #110
