### ISSUE TITLE
seznambot

### ISSUE THREAD

**Issue by nigelhorne** [oalders/http-browserdetect#131]
Please add seznambot, the Czech search engine, to the known lists of robots.

**Comment by oalders** [comment]
Did you want to send a pull request?  If not, can you provide the relevant user agent strings?

**Comment by nigelhorne** [comment]
Here's a line from my Apache access file:

77.75.76.171 - - [19/Oct/2016:08:49:09 -0700] "GET /cgi-bin/page.fcgi?page=people&home=1 HTTP/1.1" 200 4325 "-" "Mozilla/5.0 (compatible; SeznamBot/3.2; +http://napoveda.seznam.cz/en/seznambot-intro/)"

**Comment by reneeb** [comment]
This is already detected... I've added a test case for the given UA string in #142

**Comment by oalders** [comment]
Closed via #142
