### ISSUE TITLE
Warning on IE UA

### ISSUE THREAD

**Issue by oschwald** [oalders/http-browserdetect#135]
We are getting the following warning with the latest `HTTP::BrowserDetect`:

```
Argument "" isn't numeric in addition (+) at /opt/perl5.26.1/lib/site_perl/5.26.1/HTTP/BrowserDetect.pm line 2012.
```

The UA string is `Mozilla/5.0 (compatible; MSIE 7.0; Intel Mac OS X 10_8_1; Trident/)`.

**Comment by oalders** [comment]
Not that it matters for the fix, but is this a spoofed UA?  I would expect a version after `Trident/`.

**Comment by oschwald** [comment]
Given that the last version of IE for macOS was 5, I think it is safe to assume that this is a spoofed UA.

**Comment by oalders** [comment]
This appears to be fixed now.
