### ISSUE TITLE
HeadlessChrome not identified as a robot

### ISSUE THREAD

**Issue by dianomi-mjs** [oalders/http-browserdetect#183]
Hi

We see user agents for headless chrome now eg

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/79.0.3945.0 Safari/537.36

These are not picked up by isRobot. Could they be, like BingPreview is?

**Comment by oalders** [comment]
Hi @dianomi-mjs,

Thanks for reporting this. This sounds like something we should do. I would certainly accept a pull request for this.

**Comment by robrwo** [comment]
:+1: 

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/86.0.4240.75 Safari/537.36
