### ISSUE TITLE
Can't see how to test my system

### ISSUE THREAD

**Issue by robertII** [oalders/http-browserdetect#185]
I'm porting an eight-year-old Perl application to new version of everything, including Catalyst.
And the tests are failing.

The application tries to protect some pages (e.g. those containing personal information) from being accessed by robots.
Which it does by calling `$browser->robot()`: if this says the query is from a robot, the system won't let it have the page.  Far from perfect, but that's the way it is...

The new problem is arising in testing, which uses `Test::WWW::Mechanize`,
because `HTTP::BrowserDetect` is (correctly) recognising `Test::WWW::Mechanize` as a robot.
And so the system is not allowing it to try to log in...

What is the recommended way to tackle this?  
I don't want to have to modify the actual system to behave differently when under test.
Or, indeed, to rip out the (less than perfect) information protection mechanism.

So I'm left with trying to change every one of the (large number of) calls to `Test::WWW::Mechanize::Catalyst` to specify an "agent" string that `BrowserDetect` wouldn't recognise.  Which seems, well, less than elegant.

Is there a better way to do this? 
The "right" answer seems to be to tell `BrowserDetect` that, right now, in its current environment, it should pretend that "Test-WWW-Mechanize/1.52" is not a robot...
Is there a way to do that, or something like it?

**Comment by oalders** [comment]
That's a very good question. I've been maintaining this module for a long time and I think this is the first time it has come up. :)

I think, ideally, you'd have some kind of a test helper class that could create the `Test::WWW::Mechanize::Catalyst` object for you with the user agent string that works for you. It sounds like you'd have a fair bit of refactoring to do in order to implement that.

You could also subclass `HTTP::BrowserDetect` and override some of the robot detection logic when in the test environment, i.e. `$ENV{HARNESS_ACTIVE}` is true.

You could also do something like `local *HTTP::BrowserDetect::robot = sub { 0 };` in the tests where it matters. 

It's an interesting problem. The module hasn't changed all that much since I've been involved. It was never built with configurability in mind.

Off the top of my head, rigging the user agent string in the tests would be the least surprising way to do this, but it's probably also the most tedious.

**Comment by robertII** [comment]
First off, thanks for the prompt response, and "keep up the good work" on the package(s).


> 
> That's a very good question. I've been maintaining this module for a long time and I think this is the first time it has come up. :)

Whereas I was thinking "I can't be the first person to have hit this problem -- there must be 'a way to do it' (perhaps even MORE than one way to do it:-).

Mind you, I was pretty surprised when I realised that `Test::WWW::Mechanize` being flagged as a ruby library!

> 
> I think, ideally, you'd have some kind of a test helper class that could create the `Test::WWW::Mechanize::Catalyst` object for you with the user agent string that works for you. It sounds like you'd have a fair bit of refactoring to do in order to implement that.

Some, yes....

> 
> You could also subclass `HTTP::BrowserDetect` and override some of the robot detection logic when in the test environment, i.e. `$ENV{HARNESS_ACTIVE}` is true.

> 
> You could also do something like `local *HTTP::BrowserDetect::robot = sub { 0 };` in the tests where it matters.
Unfortunately, that's almost all the tests (except the one that exercises the anti-robot activity).

> 
> It's an interesting problem. The module hasn't changed all that much since I've been involved. It was never built with configurability in mind.

I guess I was expecting that `HTTP::BrowserDetect` would have some mechanism for being told it was in a test harness -- perhaps registering a "HARNESS_AGENT_STRING" somewhere -- and that `Test::WWW::Mechanize::Catalyst` would use that mechanism to tell `HTTP::BrowserDetect` to chill...

> 
> Off the top of my head, rigging the user agent string in the tests would be the least surprising way to do this, but it's probably also the most tedious.

I'm actually thinking that right now, I'm going to simply disable the "reject robots" code.   
Then, once I am sure the rest of the system is working (and I can stop paying for the old servers!), I'll think about whether it is worth tweaking things so that I can re-enable it.

**Comment by oalders** [comment]
> First off, thanks for the prompt response, and "keep up the good work" on the package(s).

Thanks. :)

> Mind you, I was pretty surprised when I realised that Test::WWW::Mechanize being flagged as a ruby library!

Yes, that is surprising! I'm guessing that may predate my involvement.

Good luck with getting all of your dependencies updated. I'll close this issue for now, but feel free to revisit this or open another if there's anything else you want to to over.
