### ISSUE TITLE
IE Mode in Edge

### ISSUE THREAD

**Issue by FloppyKing** [oalders/http-browserdetect#186]
Sorry, I realize this likely isn't the best place to post this, but I wasn't sure how else to communicate with the developers of this module.

Is there currently a way to detect server side if the browser in use is Edge, but specifically with IE mode enabled or at least if it has the capability to have IE mode be enabled?

**Comment by FloppyKing** [comment]
related info https://stackoverflow.com/questions/66371262/detecting-browser-in-edge-ie-mode

**Comment by oalders** [comment]
I'm no expert on that, but is this helpful https://docs.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-guidance?
