### ISSUE TITLE
Samsung Browser for Android is detected as Chrome

### ISSUE THREAD

**Issue by oschwald** [oalders/http-browserdetect#191]
This browser appears to be a Blink-based browser that is similar but not the same as Chrome. Here is an example UA:

```
Mozilla/5.0 (Linux; Android 8.1.0; SAMSUNG SM-G610M) AppleWebKit/537.36 (    KHTML, like Gecko) SamsungBrowser/14.2 Chrome/87.0.4280.141 Mobile Safari/537.36
```

The browser string is [currently "Chrome"](https://browserdetect.org/?ua=Mozilla%2F5.0+%28Linux%3B+Android+8.1.0%3B+SAMSUNG+SM-G610M%29+AppleWebKit%2F537.36+%28++++KHTML%2C+like+Gecko%29+SamsungBrowser%2F14.2+Chrome%2F87.0.4280.141+Mobile+Safari%2F537.36).

I also wonder if `blink` would make more sense as the engine, but that is orthogonal.

**Comment by oalders** [comment]
What should this ideally be returning for the browser? `Chromium` with `blink` as the engine?

Current output is https://www.browserdetect.org/?ua=Mozilla%2F5.0+%28Linux%3B+Android+8.1.0%3B+SAMSUNG+SM-G610M%29+AppleWebKit%2F537.36+%28++++KHTML%2C+like+Gecko%29+SamsungBrowser%2F14.2+Chrome%2F87.0.4280.141+Mobile+Safari%2F537.36

**Comment by oalders** [comment]
See also https://github.com/oalders/http-browserdetect/issues/164

**Comment by oschwald** [comment]
`uasurfer` for Go returns just `Samsung`.  The [description on Google Play](https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser&hl=en_US&gl=US) seems to use "Samsung Internet Browser" and "Samsung Internet".

I think I'd expect the browser to be pretty specific, e.g., "Samsung", rather than "Chromium". For engine, I'd expect all of the Chromium-based browsers, e.g., Chrome, Opera, Edge, this one, to have `blink` as the engine.
