### ISSUE TITLE
Kindle Fires not detected as mobile or tablet

### ISSUE THREAD

**Issue by andrewt-photobox** [oalders/http-browserdetect#52]
Kindle Fires are not detected as mobile or tablet.

In case it helps, I'm deriving user agent strings from:
https://developer.amazon.com/sdk/fire/specifications.html
and:
http://docs.aws.amazon.com/silk/latest/developerguide/user-agent.html

**Comment by andrewmoise** [comment]
This should be fixed as of version 2.01.
