### ISSUE TITLE
Obigo browser is not detected as mobile

### ISSUE THREAD

**Issue by als1** [oalders/http-browserdetect#93]
Obigo is apparently a mobile browser, but HTTP::BrowserDetect usually does not detect it as mobile. The wikipedia description suggests that it's used by WAP as well as smartphones, but I've only seen WAP user-agents in our logs in recent days. But it's clearly being used by WAP phones. Here is the Obigo Browser description:

https://en.wikipedia.org/wiki/Obigo_Browser

Here are some sample user agents. Sometimes the user-agent is detected as WAP but not mobile, and sometimes the browser string is extracted, sometimes it isn't. Interestingly, the fist user-agent is detected as mobile and WAP, but no browser string is extracted.

ALCATEL_A392G/1.0 ObigoInternetBrowser/Q05A[TF013513003477632000000018014935480]
mobile: 1 wap: 1 browser_string: 

LG-LG306G/V100[TF013948006538818000000018064370513] Obigo/Q7.3 Profile/MIDP-2.1 Configuration/CLDC-1.1
mobile:  wap: 1 browser_string: Obigo

MOT-EX431G/[TF359486041608603004831018142290921] Obigo/Q03C MMP/2.0
mobile:  wap: 1 browser_string: Obigo

HUAWEI-H215G/1.0[TF860495020075686000000017029451468] Obigo-Browser/Q05A MMS/UNIBOX/V1.2 HuaweiJava/1.0 Profile/MIDP-2.0 Configuration/CLDC-1.1
mobile:  wap:  browser_string: 

I was testing with HTTP::BrowserDetect 1.75 (most recent, I believe).

% perl -MHTTP::BrowserDetect -le '$ua=HTTP::BrowserDetect->new("LG-LG306G/V100[TF013948006538818000000018064370513] Obigo/Q7.3 Profile/MIDP-2.1 Configuration/CLDC-1.1"); print "package version: $HTTP::BrowserDetect::VERSION  mobile: ".$ua->mobile." wap: ".$ua->wap." browser_string: ".$ua->browser_string'
package version: 1.75  mobile:  wap: 1 browser_string: Obigo

**Comment by andrewmoise** [comment]
It looks to me like this is fixed with the v3.13 Obigo fixups (all four of those user agents set the tests "wap", "mobile", "obigo", and "device", and they all return Obigo for browser() and browser_string()).
